services:
  caff_node:
    image: ghcr.io/espressosystems/nitro-espresso-integration/nitro-node@sha256:9e1c11a95df5549501f6cc4833cb4acee9b5d860178109d7e4c1230948ed3773
    container_name: caff_node
    ports:
      - "8550:8547"
      - "8551:8548"
      - "8552:8549"
    command: --conf.file /config/caff_node.json
    volumes:
      - ./config:/config
      - ./wasm:/home/user/wasm/
      - ./database:/home/user/.arbitrum
